---

Group members: William Patsios, Edward Tong, Aditya Srinivasan
Output type: html_document

---
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(ggplot2)
library(tidyverse)
library(tidyr)
library(dplyr)
library(tibble)
library(askpass)
library(datasets)
library(lubridate)

```
####I. Introduction

Hello! Welcome to the Data Science Tutorial! We will teach you how to work with R and how to work with datasets!
```{r}
data <- read_csv("data/COVID19_line_list_data.csv")
data
```


Next, we select the columns that we are interested in. For our purposes, we only need `time`, `latitude`, `longitude`, `depth`, `mag`, `magType`, and `place`.
```{r}
simple_data <- data %>%
  select("reporting date", "country", "gender", "age")
simple_data
```

```{r}
library(lubridate)
simple_data <- simple_data %>%
  mutate(date=mdy(simple_data$`reporting date`))%>%
  select(-"reporting date")
simple_data
```

####Statistical Analysis

Want to see if correlation between gender and number of cases


```{r}

```

```{r}
female_data <- simple_data %>%
  filter(gender == "female") %>%
  group_by(country, date) %>%
  summarize(cases=n()) %>%
  mutate(case_total=cumsum(cases))
male_data <- simple_data %>%
  filter(gender == "male") %>%
  group_by(country, date) %>%
  summarize(cases=n()) %>%
  mutate(case_total=cumsum(cases))

male_data %>% ggplot(aes(x=date, y=case_total, color=country)) + geom_line() + labs(title="Reported Male Cases") + ylim(0, 125)
female_data %>% ggplot(aes(x=date, y=case_total, color=country)) + geom_line() + labs(title="Reported Female Cases") + ylim(0, 125)
```
